apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: vulnerable-httpd
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    deployment: frontend
  sessionAffinity: None
  type: ClusterIP
